### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by leoheitmannruiz** [vimium/vimium.github.io#2]
Hey,

I feel like the project would benefit in vimium.github.io being redesigned. You can view my idea at https://leoheitmannruiz.github.io.

Fell free to take or leave whatever you are interested in.

- vector graphic logo
- favicon
- dark mode
- different video for dark mode and light mode (currently a placeholder, but if you are interested, I will gladly record two videos)
- looks good on mobile
- a few small changes in wording and stuff

Edit: As I've deleted the repository mentioned above, here's the content for potential future reference [site.zip](https://github.com/user-attachments/files/19525811/site.zip)

**Comment by philc** [comment]
This is great Leo! I certainly would like to lift some of the elements that you have here. I'll take a closer look in a week or so.

**Comment by philc** [comment]
hey @leoheitmannruiz, I'm impressed that you 1) found this repo and 2) decided to publish a vision for a new site layout. This was super helpful.

I've pushed a new version of the page which uses many pieces from your mockup. I saw a few small layout issues related to responsive layouts, but nothing serious -- let me know if you spot anything. Cheers!

**Comment by leoheitmannruiz** [comment]
Thanks for taking the time!

- The bullet points of the unordered list are not "indented", but rather to the left of the content (not sure how to describe it). When decreasing the width of the browser, only the right half of the bullet points is visible. I think it would look better, if they were indented, as when viewing the site on mobile (low width).
- I feel like the line saying "Install for your browser:" is not necessary
- I think displaying Chrome, Edge and Firefox in an unordered list would look good
- A few HTML warnings/errors https://validator.w3.org/nu/?doc=https%3A%2F%2Fvimium.github.io%2F

If you are interested, I will create a PR changing/fixing these few things.

**Comment by leoheitmannruiz** [comment]
Also, what do you think about having vimium.github.io as the GitHub repo URL, instead of the chrome web store. And, linking to vimium.github.io at the Firefox Add-ons site "Homepage" link, instead of the GitHub repo.
